version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: nexus-postgres
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus-password
      POSTGRES_DB: nexus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus -d nexus"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nexus-network

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Dnexus.datastore.enabled=true -Dnexus.datastore.nexus.jdbcUrl=jdbc:postgresql://postgres:5432/nexus -Dnexus.datastore.nexus.username=nexus -Dnexus.datastore.nexus.password=nexus-password -Dnexus.datastore.nexus.maximumPoolSize=10
    volumes:
      - /opt/nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - nexus-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "5443:5443"
    volumes:
      - ./192.168.20.138-key.pem:/etc/nginx/cert-key.pem
      - ./192.168.20.138.pem:/etc/nginx/cert.pem
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nexus
    networks:
      - nexus-network
networks:
  nexus-network:
    driver: bridge

volumes:
  postgres_data:
